config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :music_records
  resources :orders, only: [:index, :create]
  resources :rentals, only: [:index, :create]
  root "music_records#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/music_record.rb
class MusicRecord < ApplicationRecord
  has_one_attached :photo

  validates :title, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :music_record
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :music_record
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { user: 'user', manager: 'manager', admin: 'admin' }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/music_records_controller.rb
class MusicRecordsController < ApplicationController
  before_action :set_music_record, only: [:show, :edit, :update, :destroy]

  def index
    @music_records = MusicRecord.all
  end

  def show
  end

  def new
    @music_record = MusicRecord.new
  end

  def edit
  end

  def create
    @music_record = MusicRecord.new(music_record_params)
    if @music_record.save
      redirect_to @music_record, notice: 'Music record was successfully created.'
    else
      render :new
    end
  end

  def update
    if @music_record.update(music_record_params)
      redirect_to @music_record, notice: 'Music record was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @music_record.destroy
    redirect_to music_records_url, notice: 'Music record was successfully destroyed.'
  end

  private

  def set_music_record
    @music_record = MusicRecord.find(params[:id])
  end

  def music_record_params
    params.require(:music_record).permit(:title, :description, :price, :damage_assessment, :photo)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to orders_path, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :music_record_id)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @rentals = Rental.all
  end

  def create
    @rental = Rental.new(rental_params)
    if @rental.save
      redirect_to rentals_path, notice: 'Rental was successfully created.'
    else
      render :new
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:user_id, :music_record_id, :rent_date, :price, :note, :damage_assessment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/music_records_helper.rb
module MusicRecordsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicRecordStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/music_records/_form.html.erb
<%= form_with(model: music_record, local: true) do |form| %>
  <% if music_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(music_record.errors.count, "error") %> забороняє зберегти цей запис:</h2>
      <ul>
        <% music_record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :damage_assessment %>
    <%= form.text_field :damage_assessment %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/music_records/edit.html.erb
<h1>Edit Music Record</h1>

<%= render 'form', music_record: @music_record %>

<%= link_to 'Back', music_records_path %>

app/views/music_records/index.html.erb
<h1>Music Records</h1>

<%= link_to 'New Music Record', new_music_record_path %>

<ul>
  <% @music_records.each do |music_record| %>
    <li>
      <%= link_to music_record.title, music_record %>
      (<%= link_to 'Edit', edit_music_record_path(music_record) %>,
       <%= link_to 'Destroy', music_record, method: :delete, data: { confirm: 'Are you sure?' } %>)
    </li>
  <% end %>
</ul>

app/views/music_records/new.html.erb
<h1>New Music Record</h1>

<%= render 'form', music_record: @music_record %>

<%= link_to 'Back', music_records_path %>

app/views/music_records/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @music_record.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @music_record.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @music_record.price %>
</p>

<p>
  <strong>Damage Assessment:</strong>
  <%= @music_record.damage_assessment %>
</p>

<% if @music_record.photo.attached? %>
  <p>
    <strong>Photo:</strong>
    <%= image_tag @music_record.photo %>
  </p>
<% end %>

<%= link_to 'Edit', edit_music_record_path(@music_record) %> |
<%= link_to 'Back', music_records_path %>